### PR TITLE
Container for old build instructions

### PR DESCRIPTION
**Pull request by roma-guru**
Here is basic draft version of Dockerfile with ubuntu 12.04. Tested once under Windows 8 with Docker Toolbox. I'll test it again from the ground up and under Linux also.

### CODE REVIEW

**Comment by auchri** [comment]
I'm currently trying to automatically build the image at [Travis](https://travis-ci.org), but Qt uses too much space 😢 
https://travis-ci.org/telegramdesktop/docker/jobs/290124095

**Comment by roma-guru** [comment]
> The job exceeded the maximum time limit for jobs, and has been terminated

Is there a way to increase time limit?
I have successfully built the image on Linux Mint (with native docker) - but it tooks 40 minutes on my machine.

**Comment by auchri** [comment]
@roman-voropaev No, that's not possible 😕
You have to divide the image into multiple stages, like I did in my branch. But still qt won't build because it uses too much disk space.

**Comment by roma-guru** [comment]
@auchri OK, I will try this with a new pull request then. Where may I see your branch?

**Comment by auchri** [comment]
@roman-voropaev Can you contact me on Telegram? @auchri

**Comment by auchri** [comment]
There are the files of an working commit: https://github.com/telegramdesktop/docker/tree/2bca52904013ca81e8ed85232c11a2abd52fd95e

**Pull request closed without merging**
